### ISSUE TITLE
Update the server to Java version that Geyser requires (1.19.3)

### ISSUE THREAD

**Issue by tomsalmonza** [TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate#11]
[17:04:15 WARN]: [Geyser-Spigot] Your server software does not support the Java version that Geyser requires (1.19.3). 

Thanks

**Comment by tomsalmonza** [comment]
I see this was maybe dealt with in #10 ?
However I still get the error with latest.

**Comment by TheRemote** [comment]
This should be taken care of now here.  Paper 1.19.3 is now out (make backups first).

Enjoy and take care!
