### ISSUE TITLE
TrueNAS Scale Support

### ISSUE THREAD

**Issue by jimsimon** [TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate#20]
This might be a bit of an obscure request, but would it be possible for you to add the necessary config to be able to deploy this container on TrueNAS Scale? Third party "apps" (docker services running via k8s) can be installed via a community repo called TrueCharts. I believe it uses helm charts for the configuration. The documentation is here if you're at all interested in doing this: https://truecharts.org/manual/development/chart-structure

If you're not able to then I may attempt to do it myself and open a PR once my server parts arrive and I have it set up (likely a few weeks minimum).

**Comment by TheRemote** [comment]
Hello,

I don't have access to one of these but I would be more than willing to add the configuration in!  I've done similar things for Kubernetes which wasn't originally supported.  That was a PR basically someone submitted.

I'd be willing to do the same thing for this if you're able to do this!

**Comment by jimsimon** [comment]
Sure thing. I think you can run it in a VM as well since it's just based on Debian Linux. Ill try to get a PR up for it once I'm able to play around more.

**Comment by TheRemote** [comment]
Thanks, let me know if you get it going!

**Comment by vandoeselaar** [comment]
You can run this as a "custom app" in truenas scale without any problems.
