### ISSUE TITLE
PaperMC config is overwritten on every start

### ISSUE THREAD

**Issue by karl007** [TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate#21]
Hi.

It seems there is a change in configuration concept of papermc. The paper.yml is no longer used, instead there is a paper-global.yml and a paper-world-defaults.yml in the /config folder.

On every start, PaperMC find the deprecated paper.yml, move this to the /config/legacy folder and create the two new config files above.
On the next Docker (and start.sh) start, the paper.yml is missing and copied again.

As hotfix, I extend the docker image, remove the paper.yml part from the start.sh and papermc keeps my changes in paper-world-defaults.yml.

**Comment by TheRemote** [comment]
Thanks for reporting this!  I've updated to paper-global.yml in the latest version.

Take care!
