### ISSUE TITLE
Bedrock Update 1.20.30 ?

### ISSUE THREAD

**Issue by tunafishman** [TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate#24]
The switch won't connect to the server after an update today. Mojang lists a new version roll-out [today](https://feedback.minecraft.net/hc/en-us/articles/19545277817357-Minecraft-1-20-30-Bedrock-)

Is the fix for that just a replay of [this commit](https://github.com/TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate/commit/e05817246e326c9555f179c020d90ca05961f929) but with `:s/1.20.1/1.20.2` ?

**Comment by tunafishman** [comment]
The downstream consequences of these updates is wild to follow. Watching Paper devs apply patches and release builds is kinda cool. Not sure what's required of the other packages like Spigot and Floodgate and ViaVersion but it's pretty amazing the work that goes in to this community.

**Comment by TheRemote** [comment]
Yes, that should be the issue.  You need to be running 1.20.2 for ViaVersion to support 1.20.30.

I've updated the images but you can always update it yourself with -e Version=1.20.2

Paper / ViaVersion / Floodgate are indeed doing all of the work here.  All I did to update for this version was change the default version to 1.20.2.  There are no other changes and this is controlled by you with -e Version=1.X.X.

Hopefully that helps!
