### ISSUE TITLE
 Where are the creatures?

### ISSUE THREAD

**Issue by cap-blackbeard** [TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate#26]
I used a Bedrock server. We had named lots of villagers and other creatures.
Then I converted this Bedrock world using the Chunker tool to a Java world and started the Legendary-Java-Minecraft-Geyser-Floodgate-Server.
Now, when I enter the world, there are no creatures left. Can anyone explain to me? Or does anyone have experience with the options in Chunker or the new Server?

**Comment by tywil04** [comment]
> Chunker can currently convert:
> - Level settings
> - World data (blocks, biomes, and tile entities)
> - Multiple dimensions
> - Container & items
> - In-game maps
>
> Chunker cannot currently convert:
> - Entities
> - Player inventories

From https://learn.microsoft.com/en-us/minecraft/creator/documents/chunkeroverview?view=minecraft-bedrock-stable.

**Comment by cap-blackbeard** [comment]
Thank you very much for your help. Sometimes I can't see the forest for the trees.
