### ISSUE TITLE
Backups not being made

### ISSUE THREAD

**Issue by RayRaytheGrape** [TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate#30]
Hey guys, about a year ago I was running my server with backups set to 1 using -e Backupcount=1
Now even when setting it to a number like 10 or 20 no backups are made.

**Comment by zerofai** [comment]
The backup works for me. But I have not using Env to change numbers of backup

**Comment by DanGarion** [comment]
I'm experiencing the same issue. Backups worked up until August 22nd 2023. No more backups since then.

**Comment by RayRaytheGrape** [comment]
> I'm experiencing the same issue. Backups worked up until August 22nd 2023. No more backups since then.

If you changed the name of your world folders then the backups stop. That's what James told me the issue was and it was fixed. I'd also try pulling the latest version.

**Comment by DanGarion** [comment]
So, I need to change the names back to the default?

**Comment by RayRaytheGrape** [comment]
> So, I need to change the names back to the default?

Yes that should fix it.
