### ISSUE TITLE
server is on 1.21 not 1.21.3 How to update?

### ISSUE THREAD

**Issue by siparker** [TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate#36]
I tried to connect today and am unable as it says the server version is 1.21 not sure if it is because my minecraft version is 1.21.3 and not 1.21.0 or something else. 
I have restarted docker but im not sure where to look to figure it out. 
Paper says to just replace with the new version and update the start command to look at the new version. but i am not sure if this will affect geyser and other config here.

**Comment by codekain** [comment]
im not sure what the correct way is but i downloaded the beta version of papermc from the papermc website into the versions folder matching they file naming scheme. then just set the version in my docker compose to be 1.21.3 and rebooted and it worked for me

**Comment by TheRemote** [comment]
-e Version=1.21.3 on your startup line
