### ISSUE TITLE
Enabling RCON

### ISSUE THREAD

**Issue by cconde** [TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate#4]
Hello,

I'm unable to enable RCON, is there any environment variable for that?

Editing server.properties doesn't seem to work

Thanks and please excuse me!!!!

**Comment by TheRemote** [comment]
Hey cconde,

Hmmmm, great question, that's not one I've ever got before!  So there isn't an environment variable for it but I think I know how you may be able to get it working.

The first thing is make sure the server/container is completely closed before editing server.properties and enabling rcon.  You will also want to set a password as if it actually lets you enable it without one it shouldn't.

Assuming you have both of those done the other thing we need to do is open the port with your Docker launch command line.  This would be similar to adding an environment variable but we are only going to do the port part like this:

`docker run -it -v yourvolumename:/minecraft -p 25565:25565 -p 19132:19132/udp -p 19132:19132 -p 25575:25575 05jchambers/legendary-minecraft-geyser-floodgate:latest`

Notice that I added -p 25575:25575 (the default rcon port) at the end of the line before the 05jchambers part.  This should open up the Docker port and let rcon work as long as it has been enabled and a password has been set.  Can you give that a try here?

**Comment by cconde** [comment]
Maybe the problem is that I edited server.properties while the container was up.

Somehow I was expecting that after restarting the docker this file was re-read, but instead I was losing my changes.

I will try again with container down...

**Comment by cconde** [comment]
It worked, thanks!!!

**Comment by TheRemote** [comment]
No problem at all, enjoy and take care!
